const versionSelect = document.querySelector("#version");
const askForm = document.querySelector("#ask-form");
const queryInput = document.querySelector("#query");
const answerBox = document.querySelector("#answer");
const sourcesBox = document.querySelector("#sources");
const ingestButton = document.querySelector("#ingest");

/**
 * Load documentation versions from the API and populate the version selector.
 */
async function loadVersions() {
  const response = await fetch("/api/versions");
  const payload = await response.json();
  versionSelect.innerHTML = "";
  for (const version of payload.versions) {
    const option = document.createElement("option");
    option.value = version;
    option.textContent = version.toUpperCase();
    option.selected = version === payload.default;
    versionSelect.append(option);
  }
}

askForm.addEventListener("submit", async (event) => {
  event.preventDefault();
  answerBox.textContent = "Searching local documentation...";
  sourcesBox.innerHTML = "";
  const button = askForm.querySelector("button");
  button.disabled = true;

  try {
    const response = await fetch("/api/ask", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        version: versionSelect.value,
        query: queryInput.value,
      }),
    });
    const payload = await response.json();
    if (!response.ok) {
      throw new Error(payload.detail || "Request failed");
    }
    answerBox.textContent = payload.answer || "No answer returned.";
    renderSources(payload.sources || []);
  } catch (error) {
    answerBox.textContent = error.message;
  } finally {
    button.disabled = false;
  }
});

ingestButton.addEventListener("click", async () => {
  answerBox.textContent = "Ingesting documentation. This can take a while for full JDK docs...";
  ingestButton.disabled = true;
  try {
    const response = await fetch("/api/ingest", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ version: versionSelect.value }),
    });
    const payload = await response.json();
    if (!response.ok) {
      throw new Error(payload.detail || "Ingest failed");
    }
    answerBox.textContent = `Ingested ${payload.documents} documents into ${payload.chunks} chunks.`;
  } catch (error) {
    answerBox.textContent = error.message;
  } finally {
    ingestButton.disabled = false;
  }
});

/**
 * Render retrieved source snippets below the answer.
 *
 * The source data comes from the API, so values are escaped before entering the
 * HTML template.
 */
function renderSources(sources) {
  sourcesBox.innerHTML = "";
  for (const source of sources) {
    const item = document.createElement("article");
    item.className = "source";
    item.innerHTML = `
      <strong>${escapeHtml(source.title || source.path)}</strong>
      <p>${escapeHtml(source.path)}</p>
      <p>${escapeHtml(source.snippet || "")}</p>
    `;
    sourcesBox.append(item);
  }
}

/**
 * Escape text before interpolating it into HTML generated by this page.
 */
function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

loadVersions().catch((error) => {
  answerBox.textContent = error.message;
});
